name: PMNameFixer
main: skyss0fly\PMNameFixer\Main
src-namespace-prefix: skyss0fly\PMNameFixer
version: 1.0.1
api: [4.0.0, 5.0.0]
description: "A plugin which allows players to have their name remove space and swap with an underscore"
author: "jasonw4331"

